export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

export const LOADING_CUSTOMER = "LOADING_CUSTOMER";
export const CUSTOMER_SUCCESS = "CUSTOMER_SUCCESS";
export const CUSTOMER_FAILED = "CUSTOMER_FAILED";
export const CUSTOMER_UPDATE = "CUSTOMER_UPDATE";

export const LOADING_PARTNER = "LOADING_PARTNER";
export const PARTNER_SUCCESS = "PARTNER_SUCCESS";
export const PARTNER_FAILED = "PARTNER_FAILED";
export const PARTNER_UPDATE = "PARTNER_UPDATE";
export const FILTERD_PARTNER = "FILTERD_PARTNER";

export const LOADING_CATEGORY = "LOADING_CATEGORY";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAILED = "CATEGORY_FAILED";

export const LOADING_ORDERS = "LOADING_ORDERS";
export const SUCCESS_ORDERS = "SUCCESS_ORDERS";
export const FAILED_ORDERS = "FAILED_ORDERS";

export const LOADING_NEAREST_PARTNERS = "LOADING_NEAREST_PARTNERS";
export const SUCCESS_NEAREST_PARTNERS = "SUCCESS_NEAREST_PARTNERS";
export const FAILED_NEAREST_PARTNERS = "FAILED_NEAREST_PARTNERS";
